### ISSUE TITLE
Schedule bug: Converting floating task to non-floating

### ISSUE THREAD

**Issue by burnflare** [CS2103AUG2016-W11-C2/main#86]
When converting a floating task to non-floating, the tasks moves to the non-floating column (correct), but it still remains is in the non-floating column (wrong)

**Comment by rachx** [comment]
Are there steps to replicate? I tried assigning times to floating tasks and they move correctly most of the time.
Can you abstract the time parsing part in prepareAdd? It can used by prepareSchedule too. Instead of 3 Add commands, maybe we can have only one Add(name, startTime, endTime) and use Optional.empty

**Comment by rachx** [comment]
Didn't see it again so I am just closing this
